version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

  web:
    build: .
    ports:
      - "8011:8080"
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend
networks:
  backend:
    driver: bridge

