version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379"
    networks:
      - backend

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app

